name: Greetings from Ygg-Drasill

on: 
  pull_request_target:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Greet User
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hail, ${{ github.actor }}! Welcome to the realms of Ygg-Drasill. Your first issue opens a new leaf on the great tree."
        pr-message: "Hail, ${{ github.actor }}! Your first pull request adds another branch to the vast canopy of Ygg-Drasill."
