name: Greetings from Yggdrasil

on: 
  pull_request_target:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Greet User
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hail, ${ env.GREETING }! Welcome to the realms of Yggdrasil. Your first issue opens a new leaf on the great tree."
        pr-message: "Hail, ${ env.GREETING }! Your first pull request adds another branch to the vast canopy of Yggdrasil."
      env:
        GREETING: ${{ github.actor }}
