name: Run Go Tests for Sleipnir 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version: 1.22

    - name: Download modules
      run: go mod download && go install github.com/goccmack/gocc
  
    - name: Generate parser
      run: chmod +x ./generate.sh && ./generate.sh

    - name: Build
      run: go build -v ./...

    - name: Test
      uses: robherley/go-test-action@109b18b0c2aea8f17d5987b2b58bce5a933b41d6 # v0.2.0
      with:
        testArguments: ./test/...
        omitPie: true
        
