name: Run Go Tests for Sleipnir 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version: 1.22

    - name: Download modules
      run: go mod download && go get github.com/goccmack/gocc && go install github.com/goccmack/gocc
  
    - name: Generate parser
      run: chmod +x ./generate.sh && ./generate.sh

    - name: Build
      run: go build -v ./cmd/sleipnir

    - name: Test
      uses: robherley/go-test-action@a612d1675dda7397d3bced585f8a2a3a8545455f # v0.4.1
      with:
        testArguments: ./test/...
        omitPie: true
        
